[package]
name = "issuebidding"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-strkey = {version = "0.0.8"}

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
